/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatTasksRouteImport } from './routes/_chat.tasks'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatOrchestratorRouteImport } from './routes/_chat.orchestrator'
import { Route as ChatAutomationsRouteImport } from './routes/_chat.automations'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatTasksIndexRouteImport } from './routes/_chat.tasks.index'
import { Route as ChatSupervisorsIndexRouteImport } from './routes/_chat.supervisors.index'
import { Route as ChatPullRequestsIndexRouteImport } from './routes/_chat.pull-requests.index'
import { Route as ChatOrchestratorIndexRouteImport } from './routes/_chat.orchestrator.index'
import { Route as ChatAutomationsIndexRouteImport } from './routes/_chat.automations.index'
import { Route as ChatTasksProcessIdRouteImport } from './routes/_chat.tasks.$processId'
import { Route as ChatSupervisorsSupervisorSeatIdRouteImport } from './routes/_chat.supervisors.$supervisorSeatId'
import { Route as ChatProcessProcessIdRouteImport } from './routes/_chat.process.$processId'
import { Route as ChatOrchestratorRootThreadIdRouteImport } from './routes/_chat.orchestrator.$rootThreadId'
import { Route as ChatAutomationsAutomationIdRouteImport } from './routes/_chat.automations.$automationId'
import { Route as ChatOrchestratorRootThreadIdTasksProcessIdRouteImport } from './routes/_chat.orchestrator.$rootThreadId_.tasks.$processId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatTasksRoute = ChatTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatOrchestratorRoute = ChatOrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsRoute = ChatAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatTasksIndexRoute = ChatTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatTasksRoute,
} as any)
const ChatSupervisorsIndexRoute = ChatSupervisorsIndexRouteImport.update({
  id: '/supervisors/',
  path: '/supervisors/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsIndexRoute = ChatPullRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatPullRequestsRoute,
} as any)
const ChatOrchestratorIndexRoute = ChatOrchestratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatOrchestratorRoute,
} as any)
const ChatAutomationsIndexRoute = ChatAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAutomationsRoute,
} as any)
const ChatTasksProcessIdRoute = ChatTasksProcessIdRouteImport.update({
  id: '/$processId',
  path: '/$processId',
  getParentRoute: () => ChatTasksRoute,
} as any)
const ChatSupervisorsSupervisorSeatIdRoute =
  ChatSupervisorsSupervisorSeatIdRouteImport.update({
    id: '/supervisors/$supervisorSeatId',
    path: '/supervisors/$supervisorSeatId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatProcessProcessIdRoute = ChatProcessProcessIdRouteImport.update({
  id: '/process/$processId',
  path: '/process/$processId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatOrchestratorRootThreadIdRoute =
  ChatOrchestratorRootThreadIdRouteImport.update({
    id: '/$rootThreadId',
    path: '/$rootThreadId',
    getParentRoute: () => ChatOrchestratorRoute,
  } as any)
const ChatAutomationsAutomationIdRoute =
  ChatAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => ChatAutomationsRoute,
  } as any)
const ChatOrchestratorRootThreadIdTasksProcessIdRoute =
  ChatOrchestratorRootThreadIdTasksProcessIdRouteImport.update({
    id: '/$rootThreadId_/tasks/$processId',
    path: '/$rootThreadId/tasks/$processId',
    getParentRoute: () => ChatOrchestratorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/automations': typeof ChatAutomationsRouteWithChildren
  '/orchestrator': typeof ChatOrchestratorRouteWithChildren
  '/plugins': typeof ChatPluginsRoute
  '/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/tasks': typeof ChatTasksRouteWithChildren
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/orchestrator/$rootThreadId': typeof ChatOrchestratorRootThreadIdRoute
  '/process/$processId': typeof ChatProcessProcessIdRoute
  '/supervisors/$supervisorSeatId': typeof ChatSupervisorsSupervisorSeatIdRoute
  '/tasks/$processId': typeof ChatTasksProcessIdRoute
  '/automations/': typeof ChatAutomationsIndexRoute
  '/orchestrator/': typeof ChatOrchestratorIndexRoute
  '/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/supervisors/': typeof ChatSupervisorsIndexRoute
  '/tasks/': typeof ChatTasksIndexRoute
  '/orchestrator/$rootThreadId/tasks/$processId': typeof ChatOrchestratorRootThreadIdTasksProcessIdRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/orchestrator/$rootThreadId': typeof ChatOrchestratorRootThreadIdRoute
  '/process/$processId': typeof ChatProcessProcessIdRoute
  '/supervisors/$supervisorSeatId': typeof ChatSupervisorsSupervisorSeatIdRoute
  '/tasks/$processId': typeof ChatTasksProcessIdRoute
  '/automations': typeof ChatAutomationsIndexRoute
  '/orchestrator': typeof ChatOrchestratorIndexRoute
  '/pull-requests': typeof ChatPullRequestsIndexRoute
  '/supervisors': typeof ChatSupervisorsIndexRoute
  '/tasks': typeof ChatTasksIndexRoute
  '/orchestrator/$rootThreadId/tasks/$processId': typeof ChatOrchestratorRootThreadIdTasksProcessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/automations': typeof ChatAutomationsRouteWithChildren
  '/_chat/orchestrator': typeof ChatOrchestratorRouteWithChildren
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/tasks': typeof ChatTasksRouteWithChildren
  '/_chat/': typeof ChatIndexRoute
  '/_chat/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/_chat/orchestrator/$rootThreadId': typeof ChatOrchestratorRootThreadIdRoute
  '/_chat/process/$processId': typeof ChatProcessProcessIdRoute
  '/_chat/supervisors/$supervisorSeatId': typeof ChatSupervisorsSupervisorSeatIdRoute
  '/_chat/tasks/$processId': typeof ChatTasksProcessIdRoute
  '/_chat/automations/': typeof ChatAutomationsIndexRoute
  '/_chat/orchestrator/': typeof ChatOrchestratorIndexRoute
  '/_chat/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/_chat/supervisors/': typeof ChatSupervisorsIndexRoute
  '/_chat/tasks/': typeof ChatTasksIndexRoute
  '/_chat/orchestrator/$rootThreadId_/tasks/$processId': typeof ChatOrchestratorRootThreadIdTasksProcessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/automations'
    | '/orchestrator'
    | '/plugins'
    | '/pull-requests'
    | '/settings'
    | '/tasks'
    | '/automations/$automationId'
    | '/orchestrator/$rootThreadId'
    | '/process/$processId'
    | '/supervisors/$supervisorSeatId'
    | '/tasks/$processId'
    | '/automations/'
    | '/orchestrator/'
    | '/pull-requests/'
    | '/supervisors/'
    | '/tasks/'
    | '/orchestrator/$rootThreadId/tasks/$processId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/'
    | '/automations/$automationId'
    | '/orchestrator/$rootThreadId'
    | '/process/$processId'
    | '/supervisors/$supervisorSeatId'
    | '/tasks/$processId'
    | '/automations'
    | '/orchestrator'
    | '/pull-requests'
    | '/supervisors'
    | '/tasks'
    | '/orchestrator/$rootThreadId/tasks/$processId'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/automations'
    | '/_chat/orchestrator'
    | '/_chat/plugins'
    | '/_chat/pull-requests'
    | '/_chat/settings'
    | '/_chat/tasks'
    | '/_chat/'
    | '/_chat/automations/$automationId'
    | '/_chat/orchestrator/$rootThreadId'
    | '/_chat/process/$processId'
    | '/_chat/supervisors/$supervisorSeatId'
    | '/_chat/tasks/$processId'
    | '/_chat/automations/'
    | '/_chat/orchestrator/'
    | '/_chat/pull-requests/'
    | '/_chat/supervisors/'
    | '/_chat/tasks/'
    | '/_chat/orchestrator/$rootThreadId_/tasks/$processId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/tasks': {
      id: '/_chat/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ChatTasksRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/orchestrator': {
      id: '/_chat/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof ChatOrchestratorRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations': {
      id: '/_chat/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof ChatAutomationsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/tasks/': {
      id: '/_chat/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof ChatTasksIndexRouteImport
      parentRoute: typeof ChatTasksRoute
    }
    '/_chat/supervisors/': {
      id: '/_chat/supervisors/'
      path: '/supervisors'
      fullPath: '/supervisors/'
      preLoaderRoute: typeof ChatSupervisorsIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests/': {
      id: '/_chat/pull-requests/'
      path: '/'
      fullPath: '/pull-requests/'
      preLoaderRoute: typeof ChatPullRequestsIndexRouteImport
      parentRoute: typeof ChatPullRequestsRoute
    }
    '/_chat/orchestrator/': {
      id: '/_chat/orchestrator/'
      path: '/'
      fullPath: '/orchestrator/'
      preLoaderRoute: typeof ChatOrchestratorIndexRouteImport
      parentRoute: typeof ChatOrchestratorRoute
    }
    '/_chat/automations/': {
      id: '/_chat/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof ChatAutomationsIndexRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
    '/_chat/tasks/$processId': {
      id: '/_chat/tasks/$processId'
      path: '/$processId'
      fullPath: '/tasks/$processId'
      preLoaderRoute: typeof ChatTasksProcessIdRouteImport
      parentRoute: typeof ChatTasksRoute
    }
    '/_chat/supervisors/$supervisorSeatId': {
      id: '/_chat/supervisors/$supervisorSeatId'
      path: '/supervisors/$supervisorSeatId'
      fullPath: '/supervisors/$supervisorSeatId'
      preLoaderRoute: typeof ChatSupervisorsSupervisorSeatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/process/$processId': {
      id: '/_chat/process/$processId'
      path: '/process/$processId'
      fullPath: '/process/$processId'
      preLoaderRoute: typeof ChatProcessProcessIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/orchestrator/$rootThreadId': {
      id: '/_chat/orchestrator/$rootThreadId'
      path: '/$rootThreadId'
      fullPath: '/orchestrator/$rootThreadId'
      preLoaderRoute: typeof ChatOrchestratorRootThreadIdRouteImport
      parentRoute: typeof ChatOrchestratorRoute
    }
    '/_chat/automations/$automationId': {
      id: '/_chat/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof ChatAutomationsAutomationIdRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
    '/_chat/orchestrator/$rootThreadId_/tasks/$processId': {
      id: '/_chat/orchestrator/$rootThreadId_/tasks/$processId'
      path: '/$rootThreadId/tasks/$processId'
      fullPath: '/orchestrator/$rootThreadId/tasks/$processId'
      preLoaderRoute: typeof ChatOrchestratorRootThreadIdTasksProcessIdRouteImport
      parentRoute: typeof ChatOrchestratorRoute
    }
  }
}

interface ChatAutomationsRouteChildren {
  ChatAutomationsAutomationIdRoute: typeof ChatAutomationsAutomationIdRoute
  ChatAutomationsIndexRoute: typeof ChatAutomationsIndexRoute
}

const ChatAutomationsRouteChildren: ChatAutomationsRouteChildren = {
  ChatAutomationsAutomationIdRoute: ChatAutomationsAutomationIdRoute,
  ChatAutomationsIndexRoute: ChatAutomationsIndexRoute,
}

const ChatAutomationsRouteWithChildren = ChatAutomationsRoute._addFileChildren(
  ChatAutomationsRouteChildren,
)

interface ChatOrchestratorRouteChildren {
  ChatOrchestratorRootThreadIdRoute: typeof ChatOrchestratorRootThreadIdRoute
  ChatOrchestratorIndexRoute: typeof ChatOrchestratorIndexRoute
  ChatOrchestratorRootThreadIdTasksProcessIdRoute: typeof ChatOrchestratorRootThreadIdTasksProcessIdRoute
}

const ChatOrchestratorRouteChildren: ChatOrchestratorRouteChildren = {
  ChatOrchestratorRootThreadIdRoute: ChatOrchestratorRootThreadIdRoute,
  ChatOrchestratorIndexRoute: ChatOrchestratorIndexRoute,
  ChatOrchestratorRootThreadIdTasksProcessIdRoute:
    ChatOrchestratorRootThreadIdTasksProcessIdRoute,
}

const ChatOrchestratorRouteWithChildren =
  ChatOrchestratorRoute._addFileChildren(ChatOrchestratorRouteChildren)

interface ChatPullRequestsRouteChildren {
  ChatPullRequestsIndexRoute: typeof ChatPullRequestsIndexRoute
}

const ChatPullRequestsRouteChildren: ChatPullRequestsRouteChildren = {
  ChatPullRequestsIndexRoute: ChatPullRequestsIndexRoute,
}

const ChatPullRequestsRouteWithChildren =
  ChatPullRequestsRoute._addFileChildren(ChatPullRequestsRouteChildren)

interface ChatTasksRouteChildren {
  ChatTasksProcessIdRoute: typeof ChatTasksProcessIdRoute
  ChatTasksIndexRoute: typeof ChatTasksIndexRoute
}

const ChatTasksRouteChildren: ChatTasksRouteChildren = {
  ChatTasksProcessIdRoute: ChatTasksProcessIdRoute,
  ChatTasksIndexRoute: ChatTasksIndexRoute,
}

const ChatTasksRouteWithChildren = ChatTasksRoute._addFileChildren(
  ChatTasksRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatAutomationsRoute: typeof ChatAutomationsRouteWithChildren
  ChatOrchestratorRoute: typeof ChatOrchestratorRouteWithChildren
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatPullRequestsRoute: typeof ChatPullRequestsRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatTasksRoute: typeof ChatTasksRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
  ChatProcessProcessIdRoute: typeof ChatProcessProcessIdRoute
  ChatSupervisorsSupervisorSeatIdRoute: typeof ChatSupervisorsSupervisorSeatIdRoute
  ChatSupervisorsIndexRoute: typeof ChatSupervisorsIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatAutomationsRoute: ChatAutomationsRouteWithChildren,
  ChatOrchestratorRoute: ChatOrchestratorRouteWithChildren,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatPullRequestsRoute: ChatPullRequestsRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatTasksRoute: ChatTasksRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
  ChatProcessProcessIdRoute: ChatProcessProcessIdRoute,
  ChatSupervisorsSupervisorSeatIdRoute: ChatSupervisorsSupervisorSeatIdRoute,
  ChatSupervisorsIndexRoute: ChatSupervisorsIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
