export const MODEL_STRENGTH_POLICY_V1 = {
  version: 1,
  publishedAt: "2026-08-01T00:00:00.000Z",
  dimensions: [
    "architecture",
    "broad_discovery",
    "implementation",
    "ui_taste",
    "adversarial_review",
    "long_context_synthesis",
    "cost_efficiency",
    "latency",
  ],
  entries: [
    {
      provider: "codex",
      model: "gpt-5.6-sol",
      family: "openai-gpt-5.6",
      strengths: {
        architecture: 8,
        broad_discovery: 8,
        implementation: 9,
        ui_taste: 5,
        adversarial_review: 9,
        long_context_synthesis: 8,
        cost_efficiency: 9,
        latency: 6,
      },
      notes: ["Strong implementation and adversarial review", "May over-engineer open design"],
    },
    {
      provider: "claudeAgent",
      model: "sonnet-5",
      family: "anthropic-sonnet-5",
      strengths: {
        architecture: 6,
        broad_discovery: 6,
        implementation: 6,
        ui_taste: 7,
        adversarial_review: 6,
        long_context_synthesis: 7,
        cost_efficiency: 6,
        latency: 8,
      },
      notes: ["Balanced interactive execution and user-facing taste"],
    },
    {
      provider: "claudeAgent",
      model: "opus-4.8",
      family: "anthropic-opus-4.8",
      strengths: {
        architecture: 8,
        broad_discovery: 8,
        implementation: 7,
        ui_taste: 8,
        adversarial_review: 8,
        long_context_synthesis: 8,
        cost_efficiency: 7,
        latency: 5,
      },
      notes: ["Strong architecture, synthesis, and design taste"],
    },
    {
      provider: "claudeAgent",
      model: "fable-5",
      family: "anthropic-fable-5",
      strengths: {
        architecture: 9,
        broad_discovery: 9,
        implementation: 8,
        ui_taste: 9,
        adversarial_review: 9,
        long_context_synthesis: 9,
        cost_efficiency: 9,
        latency: 7,
      },
      notes: ["Preferred when available for high-taste independent design and review"],
    },
    {
      provider: "gemini",
      model: "deep-think",
      family: "google-gemini-deep-think",
      strengths: {
        architecture: 9,
        broad_discovery: 9,
        implementation: 7,
        ui_taste: 7,
        adversarial_review: 9,
        long_context_synthesis: 9,
        cost_efficiency: 5,
        latency: 3,
      },
      notes: ["Council diversity target only when live provider capability confirms availability"],
    },
  ],
  councilPreferences: {
    requireIndependentSessions: true,
    preferDifferentFamilies: true,
    preferredPrimary: { provider: "codex", model: "gpt-5.6-sol" },
    preferredShadow: { provider: "gemini", model: "deep-think" },
    unavailableTelemetryMeans: "unknown",
  },
} as const;

export type ModelStrengthPolicyV1 = typeof MODEL_STRENGTH_POLICY_V1;
